In [1]:
import anndata
import pandas as pd

# Phase Investigation

Compare cell cycle phases produced by `CellCycleScoring()` when applied:
- (total) to data from all cell types in R-Notebook 1
- (per type) to data from each cell type in CellCycleScoringCode / R-Notebook 3

Store results in dataframe for easy use

In [8]:
# data over all cells
adata = anndata.read_h5ad("../anndata.h5ad")

# data per cell type
adata_FIB = anndata.read_h5ad("../anndata_FIB.h5ad")
adata_HEK = anndata.read_h5ad("../anndata_HEK.h5ad")
adata_MCF = anndata.read_h5ad("../anndata_MCF.h5ad")

In [9]:
# Phase per cell type
FIB_phase = adata_FIB.obs['Phase']
HEK_phase = adata_HEK.obs['Phase']
MCF_phase = adata_MCF.obs['Phase']

# Phase over all cells: split into cell types
phase_total = adata.obs['Phase']
FIB_phase_total = phase_total[FIB_phase.index]
HEK_phase_total = phase_total[HEK_phase.index]
MCF_phase_total = phase_total[MCF_phase.index]

# Rename
FIB_phase.name = "Phase per type"
HEK_phase.name = "Phase per type"
MCF_phase.name = "Phase per type"
FIB_phase_total.name = "Phase total"
HEK_phase_total.name = "Phase total"
MCF_phase_total.name = "Phase total"

In [10]:
pd.crosstab(FIB_phase, FIB_phase_total)

Phase total     G1  G2M   S
Phase per type
G1              31    8   0
G2M              0  130   0
S                9   14  85

In [11]:
pd.crosstab(HEK_phase, HEK_phase_total)

Phase total     G1  G2M   S
Phase per type
G1              19    0  46
G2M              4   62  17
S                0    0  96

In [12]:
pd.crosstab(MCF_phase, MCF_phase_total)

Phase total     G1  G2M   S
Phase per type
G1              39    0   0
G2M              5   18   1
S               12    1  13

In [13]:
# construct overall summary
phase_df = pd.DataFrame({'Phase_total': phase_total, 'Phase_per_type': None})

# add data
phase_df.loc[FIB_phase.index, 'Phase_per_type'] = FIB_phase
phase_df.loc[HEK_phase.index, 'Phase_per_type'] = HEK_phase
phase_df.loc[MCF_phase.index, 'Phase_per_type'] = MCF_phase

In [14]:
pd.crosstab(phase_df['Phase_total'], phase_df['Phase_per_type'])

Phase_per_type  G1  G2M    S
Phase_total
G1              89    9   21
G2M              8  210   15
S               46   18  194

In [ ]:
# store
phase_df.to_csv("./phase.csv")