In [158]:
import pandas as pd

# Summary

- R biomaRt fetch same as Ensembl direct download `mart_export`

However

- R notebooks use 'match' to extract biotype for each gene name in dataset
- returns NA if gene name not in biotype data (currently setting to "Failure" type)
- returns the first biotype if multiple for the name (currently prioritise protein coding, then majority)

## Human

### Ensembl download

In [153]:
d_df = pd.read_csv("../../../Moment-equations/Real-Data-2/Biotypes/mart_export.txt")
d_df = d_df[['Gene name', 'Gene type']].drop_duplicates().dropna()
d_df = d_df.rename(columns={'Gene name': 'name', 'Gene type': 'type'})
d_df = d_df.set_index('name')
d_df

                   type
name
MT-TF           Mt_tRNA
MT-RNR1         Mt_rRNA
MT-TV           Mt_tRNA
MT-RNR2         Mt_rRNA
MT-TL1          Mt_tRNA
...                 ...
TSPAN1   protein_coding
AHCYL1   protein_coding
JMJD4    protein_coding
DAP3     protein_coding
YY1AP1   protein_coding

[42019 rows x 1 columns]

### Ensembl fetch

In [154]:
f_df = pd.read_csv("GRCh38.id.name.biotype.tsv", sep="\t")
f_df = f_df[['external_gene_name', 'gene_biotype']].drop_duplicates().dropna()
f_df = f_df.rename(columns={'external_gene_name': 'name', 'gene_biotype': 'type'})
f_df = f_df.set_index('name')
f_df

                   type
name
MT-TF           Mt_tRNA
MT-RNR1         Mt_rRNA
MT-TV           Mt_tRNA
MT-RNR2         Mt_rRNA
MT-TL1          Mt_tRNA
...                 ...
TSPAN1   protein_coding
AHCYL1   protein_coding
JMJD4    protein_coding
DAP3     protein_coding
YY1AP1   protein_coding

[42019 rows x 1 columns]

### Comparison

In [155]:
(d_df == f_df).all()

type    True
dtype: bool

## Mouse

### Download

In [159]:
d_df = pd.read_csv("../../Biotypes/mart_export.txt", sep="\t")
d_df = d_df[['Gene name', 'Gene type']].drop_duplicates().dropna()
d_df = d_df.rename(columns={'Gene name': 'name', 'Gene type': 'type'})
d_df = d_df.set_index('name')
d_df

                         type
name
mt-Tf                 Mt_tRNA
mt-Rnr1               Mt_rRNA
mt-Tv                 Mt_tRNA
mt-Rnr2               Mt_rRNA
mt-Tl1                Mt_tRNA
...                       ...
Fcnb           protein_coding
Gm13371                lncRNA
F730016J06Rik          lncRNA
Gm74850                lncRNA
Olfm1          protein_coding

[77735 rows x 1 columns]

### Fetch

In [160]:
f_df = pd.read_csv("GRCm38.id.name.biotype.tsv", sep="\t")
f_df = f_df[['external_gene_name', 'gene_biotype']].drop_duplicates().dropna()
f_df = f_df.rename(columns={'external_gene_name': 'name', 'gene_biotype': 'type'})
f_df = f_df.set_index('name')
f_df

                         type
name
mt-Tf                 Mt_tRNA
mt-Rnr1               Mt_rRNA
mt-Tv                 Mt_tRNA
mt-Rnr2               Mt_rRNA
mt-Tl1                Mt_tRNA
...                       ...
Fcnb           protein_coding
Gm13371                lncRNA
F730016J06Rik          lncRNA
Gm74850                lncRNA
Olfm1          protein_coding

[77735 rows x 1 columns]

### Comparison

In [161]:
(d_df == f_df).all()

type    True
dtype: bool

## R Matching just takes first biotype

### Human biotypes

In [162]:
d_df = pd.read_csv("../../../Moment-equations/Real-Data-2/Biotypes/mart_export.txt")
d_df = d_df[['Gene name', 'Gene type']].drop_duplicates().dropna()
d_df = d_df.rename(columns={'Gene name': 'name', 'Gene type': 'type'})
d_df = d_df.set_index('name')
d_df

                   type
name
MT-TF           Mt_tRNA
MT-RNR1         Mt_rRNA
MT-TV           Mt_tRNA
MT-RNR2         Mt_rRNA
MT-TL1          Mt_tRNA
...                 ...
TSPAN1   protein_coding
AHCYL1   protein_coding
JMJD4    protein_coding
DAP3     protein_coding
YY1AP1   protein_coding

[42019 rows x 1 columns]

In [181]:
f_df = pd.read_csv("../biomaRt_biotypes.csv")
f_df = f_df[['external_gene_name', 'gene_biotype']].drop_duplicates().dropna()
f_df = f_df.rename(columns={'external_gene_name': 'name', 'gene_biotype': 'type'})
f_df = f_df.set_index('name')
f_df

                            type
name
7SK                     misc_RNA
A1BG              protein_coding
A1BG-AS1                  lncRNA
A1CF              protein_coding
A2M               protein_coding
...                          ...
ZYG11B            protein_coding
ZYX               protein_coding
ZYXP1     unprocessed_pseudogene
ZZEF1             protein_coding
ZZZ3              protein_coding

[33146 rows x 1 columns]

In [203]:
d_df.loc['FAM197Y4']

                                        type
name
FAM197Y4  transcribed_unprocessed_pseudogene
FAM197Y4                              lncRNA

In [165]:
f_df.loc['FAM197Y4']

type    transcribed_unprocessed_pseudogene
Name: FAM197Y4, dtype: object

## Old version

Ensembl changed from using "HIST" for histone genes to "H" around 2020. R notebooks use "HIST" and were uploaded in 2020 so must use biotypes from before this date and change.

R notebooks also use "lincRNA" type which was retired around 2019 and combined into general "lncRNA". So must use biotypes from before this as well.

Fetch data from latest release before 2019, `may2015` (july 2019 archive unavailable)

In [166]:
o_df = pd.read_csv("GRCh38.id.name.biotype.old.tsv", sep="\t")
o_df = o_df[['external_gene_name', 'gene_biotype']].drop_duplicates().dropna()
o_df = o_df.rename(columns={'external_gene_name': 'name', 'gene_biotype': 'type'})
o_df = o_df.set_index('name')
o_df

             type
name
MT-TF     Mt_tRNA
MT-RNR1   Mt_rRNA
MT-TV     Mt_tRNA
MT-RNR2   Mt_rRNA
MT-TL1    Mt_tRNA
...           ...
PRF1     LRG_gene
RAB27A   LRG_gene
RAC2     LRG_gene
RAG1     LRG_gene
RAG2     LRG_gene

[59959 rows x 1 columns]

In [167]:
o_df['type'].unique()

array(['Mt_tRNA', 'Mt_rRNA', 'protein_coding', 'unprocessed_pseudogene',
       'lincRNA', 'transcribed_processed_pseudogene',
       'transcribed_unprocessed_pseudogene', 'processed_pseudogene',
       'antisense', 'TEC', 'polymorphic_pseudogene',
       'processed_transcript', 'IG_V_pseudogene', 'sense_intronic',
       'TR_V_gene', 'IG_J_gene', 'IG_V_gene', 'IG_C_gene', 'snoRNA',
       'misc_RNA', 'miRNA', 'rRNA', 'snRNA', 'scaRNA', 'sRNA', 'ribozyme',
       'pseudogene', 'sense_overlapping', 'IG_C_pseudogene',
       'TR_V_pseudogene', 'unitary_pseudogene', 'IG_D_gene',
       '3prime_overlapping_ncrna', 'IG_J_pseudogene', 'non_coding',
       'transcribed_unitary_pseudogene', 'TR_J_gene', 'TR_C_gene',
       'translated_processed_pseudogene',
       'translated_unprocessed_pseudogene', 'TR_D_gene',
       'TR_J_pseudogene', 'vaultRNA', 'macro_lncRNA', 'LRG_gene'],
      dtype=object)

In [168]:
[x for x in o_df.index if "HIST" in x]

['HIST1H1PS2',
 'HIST1H1A',
 'HIST1H3A',
 'HIST1H2AA',
 'HIST1H4A',
 'HIST1H3PS1',
 'HIST1H4B',
 'HIST1H2BB',
 'HIST1H2AC',
 'HIST1H3C',
 'HIST1H4C',
 'HIST1H2BA',
 'HIST1H1T',
 'HIST1H1C',
 'HIST1H2BC',
 'HIST1H2BPS1',
 'HIST1H2APS1',
 'HIST1H2APS2',
 'HIST1H2BG',
 'HIST1H2BL',
 'HIST1H2AE',
 'HIST1H2AI',
 'HIST1H2APS6',
 'HIST1H3H',
 'HIST1H3B',
 'HIST1H4K',
 'HIST1H2AJ',
 'HIST1H2AM',
 'HIST1H3I',
 'HIST1H4J',
 'HIST1H4L',
 'HIST1H2AK',
 'HIST1H1B',
 'HIST1H3J',
 'HIST1H2BPS2',
 'HIST1H2BN',
 'HIST1H2BE',
 'HIST1H3D',
 'HIST1H4D',
 'HIST1H2AD',
 'HIST1H2BF',
 'HIST1H1PS1',
 'HIST1H2AL',
 'HIST1H2BM',
 'HIST1H2AB',
 'HIST1H3E',
 'HIST1H2APS3',
 'HIST1H1D',
 'HIST2H2AA4',
 'HIST2H2AA3',
 'HIST2H4B',
 'HIST2H2BE',
 'HIST2H2BC',
 'HIST2H3A',
 'HIST2H2BD',
 'HIST1H2BO',
 'HIST2H2BF',
 'HIST2H3PS2',
 'HIST2H2BB',
 'HIST1H2BPS3',
 'HIST2H3D',
 'HIST2H3C',
 'HIST2H4A',
 'HIST2H2AC',
 'HIST1H2BJ',
 'HIST2H2AB',
 'HIST4H4',
 'HIST1H4F',
 'HIST1H1E',
 'HIST1H2BD',
 'HIST3H3',
 'HIST2H2BA',
 'HIST3H2A',
 'HIST3H2BB',
 'HIST3H2BA',
 'HIST1H2AG',
 'HIST1H4I',
 'HIST1H2BK',
 'HIST1H4G',
 'HIST1H2AH',
 'HIST1H3F',
 'HIST1H2BH',
 'HIST1H3G',
 'HIST1H2APS4',
 'HIST1H2BI',
 'HIST1H4H',
 'HIST2H3DP1',
 'HIST1H4PS1',
 'HIST1H4E']

## New Histones

In [194]:
f_df = pd.read_csv("GRCh38.id.name.biotype.tsv", sep="\t")
f_df = f_df[['external_gene_name', 'gene_biotype']].drop_duplicates().dropna()
f_df = f_df.rename(columns={'external_gene_name': 'name', 'gene_biotype': 'type'})
f_df = f_df.set_index('name')
f_df

                   type
name
MT-TF           Mt_tRNA
MT-RNR1         Mt_rRNA
MT-TV           Mt_tRNA
MT-RNR2         Mt_rRNA
MT-TL1          Mt_tRNA
...                 ...
TSPAN1   protein_coding
AHCYL1   protein_coding
JMJD4    protein_coding
DAP3     protein_coding
YY1AP1   protein_coding

[42019 rows x 1 columns]

In [195]:
hist_mask = f_df.index.str.startswith(("H1","H2","H3","H4"))
len(f_df.loc[hist_mask].index)

190

In [196]:
hist_mask = f_df.index.str.startswith(("HI"))
len(f_df.loc[hist_mask].index)

62

In [197]:
f_df = pd.read_csv("../biomaRt_biotypes.csv")
f_df = f_df[['external_gene_name', 'gene_biotype']].drop_duplicates().dropna()
f_df = f_df.rename(columns={'external_gene_name': 'name', 'gene_biotype': 'type'})
f_df = f_df.set_index('name')

In [198]:
hist_mask = f_df.index.str.startswith(("H1","H2","H3","H4"))
len(f_df.loc[hist_mask].index)

1

In [199]:
hist_mask = f_df.index.str.startswith(("HI"))
len(f_df.loc[hist_mask].index)

53

# Anndata

In [85]:
import anndata

In [88]:
adata = anndata.read_h5ad("../anndata.h5ad")
adata

AnnData object with n_obs × n_vars = 610 × 31516
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'percent.hist', 'V1', 'plate', 'celltype', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'RNA_snn_res.1', 'seurat_clusters'
    var: 'vf_vst_counts_mean', 'vf_vst_counts_variance', 'vf_vst_counts_variance.expected', 'vf_vst_counts_variance.standardized', 'vf_vst_counts_variable', 'vf_vst_counts_rank', 'var.features', 'var.features.rank'
    obsm: 'pca', 'tsne'
    layers: 'counts', 'data'
    obsp: 'nn', 'snn'

In [91]:
adata.obs['Phase']

Fibroblasts_A10_S10    G2M
Fibroblasts_A11_S11    G2M
Fibroblasts_A2_S2        S
Fibroblasts_A3_S3      G2M
Fibroblasts_A4_S4        S
                      ...
MCF7_O5_S341            G1
MCF7_O9_S345            G1
MCF7_P17_S377            S
MCF7_P3_S363            G1
MCF7_P4_S364           G2M
Name: Phase, Length: 610, dtype: object

In [117]:
min(adata.layers['counts'][:277,:].mean(axis=1))

matrix([[1.70611753]])

In [118]:
min(adata.layers['counts'][277:521,:].mean(axis=1))

matrix([[1.86130854]])

In [119]:
min(adata.layers['counts'][521:,:].mean(axis=1))

matrix([[1.77211575]])